/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models

import com.datastax.astra.devops_v2.models.Costs

import com.google.gson.annotations.SerializedName

/**
 * AvailableRegionCombination defines a tier, cloud provider, and region combination.
 * @param tier 
 * @param cloudProvider 
 * @param region 
 * @param cost 
 * @param databaseCountUsed 
 * @param databaseCountLimit 
 * @param capacityUnitsUsed 
 * @param capacityUnitsLimit 
 * @param defaultStoragePerCapacityUnitGb 
 */

data class AvailableRegionCombination (
    @SerializedName("tier")
    val tier: kotlin.String,
    @SerializedName("cloudProvider")
    val cloudProvider: kotlin.String,
    @SerializedName("region")
    val region: kotlin.String,
    @SerializedName("cost")
    val cost: Costs,
    @SerializedName("databaseCountUsed")
    val databaseCountUsed: kotlin.Int,
    @SerializedName("databaseCountLimit")
    val databaseCountLimit: kotlin.Int,
    @SerializedName("capacityUnitsUsed")
    val capacityUnitsUsed: kotlin.Int,
    @SerializedName("capacityUnitsLimit")
    val capacityUnitsLimit: kotlin.Int,
    @SerializedName("defaultStoragePerCapacityUnitGb")
    val defaultStoragePerCapacityUnitGb: kotlin.Int
)

