/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.google.gson.annotations.SerializedName

/**
 * An individual clientID and associated roles.
 * @param clientId the clientID
 * @param roles 
 */

data class ClientRole (
    /* the clientID */
    @SerializedName("clientId")
    val clientId: kotlin.String? = null,
    @SerializedName("roles")
    val roles: kotlin.collections.List<kotlin.String>? = null
)

