/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models

import com.datastax.astra.devops_v2.models.Policy

import com.google.gson.annotations.SerializedName

/**
 * The createRole model.
 * @param name The name for your custom role in your organization.
 * @param policy 
 */

data class CreateRoleRequest (
    /* The name for your custom role in your organization. */
    @SerializedName("name")
    val name: kotlin.String,
    @SerializedName("policy")
    val policy: Policy
)

