/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.google.gson.annotations.SerializedName

/**
 * CredsURL from which the creds zip may be downloaded.
 * @param downloadURL DownloadURL is only valid for about 5 minutes.
 * @param downloadURLInternal Internal DownloadURL is only valid for about 5 minutes.
 * @param downloadURLMigrationProxy Migration Proxy DownloadURL is only valid for about 5 minutes.
 * @param downloadURLMigrationProxyInternal Internal Migration Proxy DownloadURL is only valid for about 5 minutes.
 */

data class CredsURL (
    /* DownloadURL is only valid for about 5 minutes. */
    @SerializedName("downloadURL")
    val downloadURL: kotlin.String,
    /* Internal DownloadURL is only valid for about 5 minutes. */
    @SerializedName("downloadURLInternal")
    val downloadURLInternal: kotlin.String? = null,
    /* Migration Proxy DownloadURL is only valid for about 5 minutes. */
    @SerializedName("downloadURLMigrationProxy")
    val downloadURLMigrationProxy: kotlin.String? = null,
    /* Internal Migration Proxy DownloadURL is only valid for about 5 minutes. */
    @SerializedName("downloadURLMigrationProxyInternal")
    val downloadURLMigrationProxyInternal: kotlin.String? = null
)

