/**
* Astra DevOps API
* Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.0.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.squareup.moshi.Json

/**
 * ModelError information that is returned to users
 * @param message User-friendly description of error
 * @param ID API specific error code
 */

data class Error (
    /* User-friendly description of error */
    @Json(name = "message")
    val message: kotlin.String,
    /* API specific error code */
    @Json(name = "ID")
    val ID: kotlin.Int? = null
)

