/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.google.gson.annotations.SerializedName

/**
 * ModelError information that is returned to users.
 * @param message User-friendly description of error.
 * @param ID API specific error code.
 */

data class Error (
    /* User-friendly description of error. */
    @SerializedName("message")
    val message: kotlin.String,
    /* API specific error code. */
    @SerializedName("ID")
    val ID: kotlin.Int? = null
)

