/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.google.gson.annotations.SerializedName

/**
 * The response for a requested token.
 * @param clientId The ID of the client (UUID).
 * @param secret The secret token.
 * @param orgId The UUID of the organization.
 * @param roles The roles for which the token will be generated.
 * @param token AstraCS:clientId:hex(sha256(secret))
 */

data class GenerateTokenResponse (
    /* The ID of the client (UUID). */
    @SerializedName("clientId")
    val clientId: kotlin.String,
    /* The secret token. */
    @SerializedName("secret")
    val secret: kotlin.String,
    /* The UUID of the organization. */
    @SerializedName("orgId")
    val orgId: kotlin.String,
    /* The roles for which the token will be generated. */
    @SerializedName("roles")
    val roles: kotlin.collections.List<kotlin.String>,
    /* AstraCS:clientId:hex(sha256(secret)) */
    @SerializedName("token")
    val token: kotlin.String? = null
)

