/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models

import com.datastax.astra.devops_v2.models.UserResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param orgID 
 * @param orgName 
 * @param users an array of users in the organization
 */

data class GetOrganizationUsersResponse (
    @SerializedName("orgID")
    val orgID: kotlin.String,
    @SerializedName("orgName")
    val orgName: kotlin.String,
    /* an array of users in the organization */
    @SerializedName("users")
    val users: kotlin.collections.List<UserResponse>
)

