/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.google.gson.annotations.SerializedName

/**
 * A mapping of Astra node to a customer node currently in use.
 * @param originIP IP on which the node currently in use is accessible.
 * @param originPort Port on which the node currently in use is accessible.
 * @param rack The number of the rack; usually 0, 1, or 2.
 * @param rackNodeOrdinal The number of the node in a given rack, starting with 0.
 */

data class MigrationProxyMapping (
    /* IP on which the node currently in use is accessible. */
    @SerializedName("originIP")
    val originIP: kotlin.String,
    /* Port on which the node currently in use is accessible. */
    @SerializedName("originPort")
    val originPort: kotlin.Int,
    /* The number of the rack; usually 0, 1, or 2. */
    @SerializedName("rack")
    val rack: kotlin.Int,
    /* The number of the node in a given rack, starting with 0. */
    @SerializedName("rackNodeOrdinal")
    val rackNodeOrdinal: kotlin.Int
)

