/**
* Astra DevOps API
* Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.0.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.squareup.moshi.Json

/**
 * A mapping of astra node to a customer node currently in use
 * @param originIP ip on which the node currently in use is accessible
 * @param originPort port on which the node currently in use is accessible
 * @param rack the number of the rack, usually 0, 1, or 2
 * @param rackNodeOrdinal The number of the node in a given rack, starting with 0
 */

data class MigrationProxyMapping (
    /* ip on which the node currently in use is accessible */
    @Json(name = "originIP")
    val originIP: kotlin.String,
    /* port on which the node currently in use is accessible */
    @Json(name = "originPort")
    val originPort: kotlin.Int,
    /* the number of the rack, usually 0, 1, or 2 */
    @Json(name = "rack")
    val rack: kotlin.Int,
    /* The number of the node in a given rack, starting with 0 */
    @Json(name = "rackNodeOrdinal")
    val rackNodeOrdinal: kotlin.Int
)

