/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models

import com.datastax.astra.devops_v2.models.MigrationProxyMapping

import com.google.gson.annotations.SerializedName

/**
 * Configuration of the migration proxy and mappings of astra node to a customer node currently in use.
 * @param originUsername origin cassandra username
 * @param originPassword origin cassandra password
 * @param mappings 
 */

data class MigrationProxyConfiguration (
    /* origin cassandra username */
    @SerializedName("originUsername")
    val originUsername: kotlin.String,
    /* origin cassandra password */
    @SerializedName("originPassword")
    val originPassword: kotlin.String,
    @SerializedName("mappings")
    val mappings: kotlin.collections.List<MigrationProxyMapping>
)

