/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models

import com.google.gson.annotations.SerializedName

/**
 * Details of a user role and its policy details.
 * @param id The unique system generated identifier of the role.
 * @param name The name of the role.
 * @param policy
 * @param lastUpdateDatetime The date and time of the last update on the role.
 * @param lastUpdateUserid The userID of the user who last updated the role.
 */

data class Role(
    /* The unique system generated identifier of the role. */
    @SerializedName("id")
    val id: kotlin.String? = null,
    /* The name of the role. */
    @SerializedName("name")
    val name: kotlin.String? = null,
    @SerializedName("policy")
    val policy: Policy? = null,
    /* The date and time of the last update on the role. */
    @SerializedName("last_update_datetime")
    val lastUpdateDatetime: java.time.OffsetDateTime? = null,
    /* The userID of the user who last updated the role. */
    @SerializedName("last_update_userid")
    val lastUpdateUserid: kotlin.String? = null
)
