/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.google.gson.annotations.SerializedName

/**
 * 
 * @param clientName The organization name in a more human readable format.
 * @param clientId The unique identifier for the client for authentication.
 * @param clientSecret The UUID client secret for the service account from the create service account response in the user interface.
 */

data class ServiceAccountTokenInput (
    /* The organization name in a more human readable format. */
    @SerializedName("clientName")
    val clientName: kotlin.String,
    /* The unique identifier for the client for authentication. */
    @SerializedName("clientId")
    val clientId: kotlin.String,
    /* The UUID client secret for the service account from the create service account response in the user interface. */
    @SerializedName("clientSecret")
    val clientSecret: java.util.UUID
)

