/**
* Astra DevOps API
* Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.0.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.squareup.moshi.Json

/**
* 
* Values: ACTIVE,PENDING,PREPARING,PREPARED,INITIALIZING,PARKED,PARKING,UNPARKING,TERMINATED,TERMINATING,RESIZING,ERROR,MAINTENANCE,UNKNOWN
*/

enum class StatusEnum(val value: kotlin.String) {


    @Json(name = "ACTIVE")
    ACTIVE("ACTIVE"),

    @Json(name = "PENDING")
    PENDING("PENDING"),

    @Json(name = "PREPARING")
    PREPARING("PREPARING"),

    @Json(name = "PREPARED")
    PREPARED("PREPARED"),

    @Json(name = "INITIALIZING")
    INITIALIZING("INITIALIZING"),

    @Json(name = "PARKED")
    PARKED("PARKED"),

    @Json(name = "PARKING")
    PARKING("PARKING"),

    @Json(name = "UNPARKING")
    UNPARKING("UNPARKING"),

    @Json(name = "TERMINATED")
    TERMINATED("TERMINATED"),

    @Json(name = "TERMINATING")
    TERMINATING("TERMINATING"),

    @Json(name = "RESIZING")
    RESIZING("RESIZING"),

    @Json(name = "ERROR")
    ERROR("ERROR"),

    @Json(name = "MAINTENANCE")
    MAINTENANCE("MAINTENANCE"),

    @Json(name = "UNKNOWN")
    UNKNOWN("UNKNOWN");


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }
}

