/**
* Astra DevOps API
* Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.0.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.squareup.moshi.Json

/**
 * Storage contains the information about how much storage space a cluster has available
 * @param nodeCount NodeCount for the cluster
 * @param replicationFactor ReplicationFactor is the number of nodes storing a piece of data
 * @param totalStorage TotalStorage of the cluster in GB
 * @param usedStorage UsedStorage in GB
 */

data class Storage (
    /* NodeCount for the cluster */
    @Json(name = "nodeCount")
    val nodeCount: kotlin.Int,
    /* ReplicationFactor is the number of nodes storing a piece of data */
    @Json(name = "replicationFactor")
    val replicationFactor: kotlin.Int,
    /* TotalStorage of the cluster in GB */
    @Json(name = "totalStorage")
    val totalStorage: kotlin.Int,
    /* UsedStorage in GB */
    @Json(name = "usedStorage")
    val usedStorage: kotlin.Int? = null
)

