/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.google.gson.annotations.SerializedName

/**
 * Storage contains the information about how much storage space a cluster has available.
 * @param nodeCount NodeCount for the cluster.
 * @param replicationFactor ReplicationFactor is the number of nodes storing a piece of data.
 * @param totalStorage TotalStorage of the cluster in GB.
 * @param usedStorage UsedStorage in GB.
 */

data class Storage (
    /* NodeCount for the cluster. */
    @SerializedName("nodeCount")
    val nodeCount: kotlin.Int,
    /* ReplicationFactor is the number of nodes storing a piece of data. */
    @SerializedName("replicationFactor")
    val replicationFactor: kotlin.Int,
    /* TotalStorage of the cluster in GB. */
    @SerializedName("totalStorage")
    val totalStorage: kotlin.Int,
    /* UsedStorage in GB. */
    @SerializedName("usedStorage")
    val usedStorage: kotlin.Int? = null
)

