/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models

import com.google.gson.annotations.SerializedName

/**
 * TenantClusterPlanResponse is the tenant plan on a cluster.
 * @param astraOrgGUID
 * @param brokerServiceUrl
 * @param cloudProvider
 * @param cloudProviderCode
 * @param cloudRegion
 * @param clusterName
 * @param jvmVersion
 * @param plan
 * @param planCode
 * @param pulsarToken
 * @param pulsarVersion
 * @param status
 * @param tenantName
 * @param webServiceUrl
 * @param websocketQueryParamUrl
 * @param websocketUrl
 */

data class TenantClusterPlanResponse(
    @SerializedName("astraOrgGUID")
    val astraOrgGUID: kotlin.String? = null,
    @SerializedName("brokerServiceUrl")
    val brokerServiceUrl: kotlin.String? = null,
    @SerializedName("cloudProvider")
    val cloudProvider: kotlin.String? = null,
    @SerializedName("cloudProviderCode")
    val cloudProviderCode: kotlin.String? = null,
    @SerializedName("cloudRegion")
    val cloudRegion: kotlin.String? = null,
    @SerializedName("clusterName")
    val clusterName: kotlin.String? = null,
    @SerializedName("jvmVersion")
    val jvmVersion: kotlin.String? = null,
    @SerializedName("plan")
    val plan: kotlin.String? = null,
    @SerializedName("planCode")
    val planCode: kotlin.String? = null,
    @SerializedName("pulsarToken")
    val pulsarToken: kotlin.String? = null,
    @SerializedName("pulsarVersion")
    val pulsarVersion: kotlin.String? = null,
    @SerializedName("status")
    val status: kotlin.String? = null,
    @SerializedName("tenantName")
    val tenantName: kotlin.String? = null,
    @SerializedName("webServiceUrl")
    val webServiceUrl: kotlin.String? = null,
    @SerializedName("websocketQueryParamUrl")
    val websocketQueryParamUrl: kotlin.String? = null,
    @SerializedName("websocketUrl")
    val websocketUrl: kotlin.String? = null
)
