/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models

import com.google.gson.annotations.SerializedName

/**
 *
 * @param namespaceLimit
 * @param topicPerNamespaceLimit
 * @param usage A list of namespace and its usage.
 */

data class TenantLimitResponse(
    @SerializedName("namespace_limit")
    val namespaceLimit: kotlin.Int? = null,
    @SerializedName("topic_per_namespace_limit")
    val topicPerNamespaceLimit: kotlin.Int? = null,
    /* A list of namespace and its usage. */
    @SerializedName("usage")
    val usage: kotlin.collections.List<NamespaceUsage>? = null
)
