/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.google.gson.annotations.SerializedName

/**
 * The userInvite model
 * @param email The email of the user being invited
 * @param orgID The unique system generated identifier of the organization
 * @param roles 
 */

data class UserInvite (
    /* The email of the user being invited */
    @SerializedName("email")
    val email: kotlin.String,
    /* The unique system generated identifier of the organization */
    @SerializedName("orgID")
    val orgID: kotlin.String,
    @SerializedName("roles")
    val roles: kotlin.collections.List<kotlin.String>
)

