/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models

import com.datastax.astra.devops_v2.models.Role

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param userID 
 * @param email 
 * @param status The status of a user within an organization either active or invited
 * @param roles an array of roles the user belongs to for an organization
 */

data class UserResponse (
    @SerializedName("userID")
    val userID: kotlin.String,
    @SerializedName("email")
    val email: kotlin.String? = null,
    /* The status of a user within an organization either active or invited */
    @SerializedName("status")
    val status: kotlin.String? = null,
    /* an array of roles the user belongs to for an organization */
    @SerializedName("roles")
    val roles: kotlin.collections.List<Role>? = null
)

