/**
* Astra DevOps API
* Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.0.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models


import com.squareup.moshi.Json

/**
 * UserPassword specifies a username and new password. The specified password will be updated for the specified database user
 * @param username 
 * @param password New password (min 6 characters)
 */

data class UserPassword (
    @Json(name = "username")
    val username: kotlin.String? = null,
    /* New password (min 6 characters) */
    @Json(name = "password")
    val password: kotlin.String? = null
)

