/**
* Astra DevOps API
* Use these REST APIs to perform lifecycle actions for DataStax Astra databases and DataStax Astra Streaming Pulsar instances.</br>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
*
* The version of the OpenAPI document: 2.2.0
* Contact: ad-astra@datastax.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.devops_v2.models

import com.google.gson.annotations.SerializedName

/**
 * UserPassword specifies a username and new password. The specified password will be updated for the specified database user.
 * @param username
 * @param password New password (min 6 characters)
 */

data class UserPassword(
    @SerializedName("username")
    val username: kotlin.String? = null,
    /* New password (min 6 characters) */
    @SerializedName("password")
    val password: kotlin.String? = null
)
