/**
* Stargate REST API reference
* The Stargate REST API provides CRUD operations on table data managed by Stargate. Keep in mind that you will need information for the server ({databaseId} and {region}) for all of these operations.
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.stargate_v2.models


import com.squareup.moshi.Json

/**
 * Order rows storage to make use of the on-disk sorting of columns. Specifying order can make query results more efficient.
 * @param column 
 * @param order 
 */

data class ClusteringExpression (
    @Json(name = "column")
    val column: kotlin.String,
    @Json(name = "order")
    val order: ClusteringExpression.Order
) {

    /**
     * 
     * Values: ASC,DESC
     */
    enum class Order(val value: kotlin.String) {
        @Json(name = "ASC") ASC("ASC"),
        @Json(name = "DESC") DESC("DESC");
    }
}

