/**
* Stargate REST API reference
* The Stargate REST API provides CRUD operations on table data managed by Stargate. Keep in mind that you will need information for the server ({databaseId} and {region}) for all of these operations.
*
* The version of the OpenAPI document: 2.0.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.stargate_v2.models

import com.google.gson.annotations.SerializedName

/**
 *
 * @param name Name for the column, which must be unique.
 * @param typeDefinition The type of data allowed in the column.
 * @param static Denotes whether the column is shared by all rows of a partition.
 */

data class ColumnDefinition(
    /* Name for the column, which must be unique. */
    @SerializedName("name")
    val name: kotlin.String,
    /* The type of data allowed in the column. */
    @SerializedName("typeDefinition")
    val typeDefinition: ColumnDefinition.TypeDefinition,
    /* Denotes whether the column is shared by all rows of a partition. */
    @SerializedName("static")
    val static: kotlin.Boolean? = null
) {

    /**
     * The type of data allowed in the column.
     * Values: ASCII,TEXT,VARCHAR,TINYINT,SMALLINT,INT,BIGINT,VARINT,DECIMAL,FLOAT,DOUBLE,DATE,DATE_RANGE_TYPE,DURATION,TIME,TIMESTAMP,UUID,TIMEUUID,BLOB,BOOLEAN,COUNTER,INET,POINT_TYPE,LINE_STRING_TYPE,POLYGON_TYPE,FROZEN,LIST,MAP,SET,TUPLE
     */
    enum class TypeDefinition(val value: kotlin.String) {
        @SerializedName(value = "ascii")
        ASCII("ascii"),

        @SerializedName(value = "text")
        TEXT("text"),

        @SerializedName(value = "varchar")
        VARCHAR("varchar"),

        @SerializedName(value = "tinyint")
        TINYINT("tinyint"),

        @SerializedName(value = "smallint")
        SMALLINT("smallint"),

        @SerializedName(value = "int")
        INT("int"),

        @SerializedName(value = "bigint")
        BIGINT("bigint"),

        @SerializedName(value = "varint")
        VARINT("varint"),

        @SerializedName(value = "decimal")
        DECIMAL("decimal"),

        @SerializedName(value = "float")
        FLOAT("float"),

        @SerializedName(value = "double")
        DOUBLE("double"),

        @SerializedName(value = "date")
        DATE("date"),

        @SerializedName(value = "DateRangeType")
        DATE_RANGE_TYPE("DateRangeType"),

        @SerializedName(value = "duration")
        DURATION("duration"),

        @SerializedName(value = "time")
        TIME("time"),

        @SerializedName(value = "timestamp")
        TIMESTAMP("timestamp"),

        @SerializedName(value = "uuid")
        UUID("uuid"),

        @SerializedName(value = "timeuuid")
        TIMEUUID("timeuuid"),

        @SerializedName(value = "blob")
        BLOB("blob"),

        @SerializedName(value = "boolean")
        BOOLEAN("boolean"),

        @SerializedName(value = "counter")
        COUNTER("counter"),

        @SerializedName(value = "inet")
        INET("inet"),

        @SerializedName(value = "PointType")
        POINT_TYPE("PointType"),

        @SerializedName(value = "LineStringType")
        LINE_STRING_TYPE("LineStringType"),

        @SerializedName(value = "PolygonType")
        POLYGON_TYPE("PolygonType"),

        @SerializedName(value = "frozen")
        FROZEN("frozen"),

        @SerializedName(value = "list")
        LIST("list"),

        @SerializedName(value = "map")
        MAP("map"),

        @SerializedName(value = "set")
        SET("set"),

        @SerializedName(value = "tuple")
        TUPLE("tuple");
    }
}
