/**
* Stargate REST API reference
* The Stargate REST API provides CRUD operations on table data managed by Stargate. Keep in mind that you will need information for the server ({databaseId} and {region}) for all of these operations.
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.stargate_v2.models

import com.datastax.astra.stargate_v2.models.ColumnDefinition
import com.datastax.astra.stargate_v2.models.PrimaryKey
import com.datastax.astra.stargate_v2.models.TableOptions

import com.squareup.moshi.Json

/**
 * 
 * @param name 
 * @param keyspace 
 * @param columnDefinitions 
 * @param primaryKey 
 * @param tableOptions 
 */

data class Table (
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "keyspace")
    val keyspace: kotlin.String? = null,
    @Json(name = "columnDefinitions")
    val columnDefinitions: kotlin.collections.List<ColumnDefinition>? = null,
    @Json(name = "primaryKey")
    val primaryKey: PrimaryKey? = null,
    @Json(name = "tableOptions")
    val tableOptions: TableOptions? = null
)

