/**
* Stargate REST API reference
* The Stargate REST API provides CRUD operations on table data managed by Stargate. Keep in mind that you will need information for the server ({databaseId} and {region}) for all of these operations.
*
* The version of the OpenAPI document: 2.0.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.datastax.astra.stargate_rest_v2.models

import com.google.gson.annotations.SerializedName

/**
 * Order rows storage to make use of the on-disk sorting of columns. Specifying order can make query results more efficient.
 * @param column The name of the column to order by.
 * @param order The clustering order.
 */

data class ClusteringExpression(
    /* The name of the column to order by. */
    @SerializedName("column")
    val column: kotlin.String,
    /* The clustering order. */
    @SerializedName("order")
    val order: ClusteringExpression.Order
) {

    /**
     * The clustering order.
     * Values: ASC,DESC
     */
    enum class Order(val value: kotlin.String) {
        @SerializedName(value = "ASC")
        ASC("ASC"),

        @SerializedName(value = "DESC")
        DESC("DESC");
    }
}
